name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build_and_test_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Consigo la versión del POM (para tag de docker)
      - name: get-pom-version
        id: pom-version
        uses: CptMokoena/maven-get-version-action@main
      # JDK 8 para build
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          cache: 'maven'
      # Run Tests & Package
      - name: Build project with Maven
        run: ./mvnw -B test package --file pom.xml
      - name: Tests with Maven
        run: ./mvnw test
      # JDK 11 para Sonar
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Envío Sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AC1
      # Paso a lowercase la versión (repo name format)
      - id: versionLowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ steps.pom-version.outputs.version }}
      # Me logeo en github registry
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      # build push DEV
      - name: Build and push DEV
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: JAR_FILE=target/shipping-service-example-${{ steps.pom-version.outputs.version }}.jar
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ steps.versionLowercase.outputs.lowercase }}-dev
      # build push STAG
      - name: Build and push STAG
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: JAR_FILE=target/shipping-service-example-${{ steps.pom-version.outputs.version }}.jar
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ steps.versionLowercase.outputs.lowercase }}-stag
      # build push PROD
      - name: Build and push PROD
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: JAR_FILE=target/shipping-service-example-${{ steps.pom-version.outputs.version }}.jar
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ steps.versionLowercase.outputs.lowercase }}-prod